services:
  postgres:
    image: postgres:16
    container_name: pelagica_collector_postgres
    environment:
      POSTGRES_USER: pelagica
      POSTGRES_PASSWORD: thisisasupersecretpasswordnoonewilleverbeabletoguess
      POSTGRES_DB: pelagica
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_db_data: